# Generated by Django 3.1.3 on 2020-11-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_auto_20201110_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='NULL', max_length=80),
        ),
    ]
