# Generated by Django 3.1.3 on 2020-11-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_auto_20201111_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='degreename',
            new_name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='companyname',
        ),
        migrations.AddField(
            model_name='student',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='studentapp.job'),
        ),
    ]
