# Generated by Django 3.1.3 on 2020-11-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_auto_20201111_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expto',
            field=models.DateField(default=None),
        ),
    ]
